### ISSUE TITLE
Write a project post 

### ISSUE THREAD

**Issue by ryukinix** [NeowayLabs/neowaylabs.github.io#8]
Our currently open source softwares projects are (to name a few of them):

+ nash
+ neosearch
+ klb
+ waveparser
+ signal
+ drm

Pick and write a project post in `_projects`. Use something like this as header:

```
---
title: "Oatmeal Cookies"
image: 
  path: /images/oatmeal-cookies-lg.jpg
  thumbnail: /images/oatmeal-cookies-400x200.jpg
  caption: "Photo from [Pexels](https://www.pexels.com)"
layout: page
---
```
